binary_sensor.floor_motion:
  friendly_name: Gang

binary_sensor.kitchen_motion:
  friendly_name: KÃ¼che

binary_sensor.livingroom_motion:
  friendly_name: Wohnzimmer

binary_sensor.wc_motion:
  friendly_name: WC
