- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
    - windDirection
    - pressure
    - humidity
    - cloudiness

- platform: mqtt
  name: mill_seconds
  state_topic: "homie/mill/on/millis/set"
  value_template: '{{ value | float / 1000 | round(3) }}'
  unit_of_measurement: s

- platform: mqtt
  name: flat_temperature
  state_topic: "homie/dev/sensor/temperature"
  qos: 0
  unit_of_measurement: "°C"

- platform: mqtt
  name: flat_humidity
  state_topic: "homie/dev/sensor/humidity"
  qos: 0
  unit_of_measurement: "%"

- platform: mqtt
  name: espresso_temperature
  state_topic: "homie/espresso/sensor/temperature"
  qos: 0
  unit_of_measurement: "°C"

- platform: mqtt
  name: espresso_humidity
  state_topic: "homie/espresso/sensor/humidity"
  qos: 0
  unit_of_measurement: "%"
